name: Zip Files
on:
  push:
    branches:
        - main  # Replace with your desired branch name
    # paths-ignore:
    #     - '.github/workflows/zip_files.yml'  # Exclude the workflow file itself

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install zip
        run: sudo apt-get install zip

      - name: Zip files
        run: zip -r files.zip icon.png manifest.json README.md config/

      - name: Commit and push zip file
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Add zip file
          file_pattern: files.zip
          branch: main  # Replace with your desired branch name
